name: vercel production

env: 
    VERCEL_OR_ID: ${{secrets.VERCEL_OR_ID}}
    VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
    push:
          branches:
                  - main

jobs:
    Deploy-Production:
            runs-on: ubuntu-latest
            steps:
                  - uses: actions/checkout@v3
                    
                  - name: Install vercel
                    run: npm install --global vercel

                  - name: Pull vercel
                    run: vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}}

                  - name: Build production
                    run: vercel build --prod --token=${{secrets.VERCEL_TOKEN}}

                  - name: Deploy
                    run: vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}

